### PR TITLE
Skip all but today events

### PR DESCRIPTION
**Pull request by Rombusevil**
Hello, I wanted this feature on the applet for my use case and since it was simple enough and I saw there was config already implemented I decided to take a go at it.
I'm not a python dev and the only way I could make it work on my machine was replacing the dependency from `AppIndicator3` to `AyatanaAppIndicator3`. 
After a quick googling I found that AyatanaAppIndicator3 is the active fork of AppIndicator3, so maybe that's useful too, if not please let me know and I can remove that change

### CODE REVIEW

**Comment by chmouel** [comment]
@Rombusevil hey iber, thanks for contributing, the change looks good to me! but about the appindicator, on which distros this is ? I am using arch atm and i assume at least the ubuntus would have appindicator at least.

either way it's possible to fallback "nicely", ie;
```python
try:
    from gi.repository import AppIndicator3 as appindicator  
expect ImportError:
     from gi.repository import AyatanaAppIndicator3 as appindicator  # type:ignore
else:
     raise Exception("Cannot find ayatana or appindicator3 library")
````

**Comment by Rombusevil** [comment]
Hi @chmouel thanks for the try except. I'm using it on Debian 12
Please let me know if it works for you too

**Comment by chmouel** [comment]
i'll fix the pylint errors among other things..

I'd like to update the README for debian12 users, did you install gnome-next-meeting from the ppa repository ?  was it **installabale** (but not running since needed this patch)

**Comment by chmouel** [comment]
thanks a lot for all your help @Rombusevil really appreciate 🙇🏻 , 

I added your change to 2.8.0

**Comment by Rombusevil** [comment]
> i'll fix the pylint errors among other things..
> 
> I'd like to update the README for debian12 users, did you install gnome-next-meeting from the ppa repository ? was it _installabale_? (but not running since needed this patch)

Thanks @chmouel! I installed the flatpak version and this patch was needed when I tried to run from source

**Pull request merged**
